GET http://localhost:3000/FKEKK

###

GET http://localhost:3000/UTeM

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Shivaranjini",
    "password": "123456",
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
    
    "username": "Shivaranjini",
    "password": "123456",
    "name": "Shivaranjini",
    "email": "ranjini3400@gmail.com"

}